# Select the velocities assignment architecture
# Possible values: 'motor_schema' or 'subsumption'
velocities_architecture: 'motor_schema'

# Select the target function
# Possible values: 'random'
#                  'nearest_uncovered'
#                  'nearest_uncovered_brush'
#                  'nearest_uncovered_circle'
#                  'nearest_unexplored'
#                  'nearest_unexplored_brush'
#                  'nearest_unexplored_circle'
#                  'best_topology'
#                  'next_best_view'
target_selector: 'best_topology'

# Debugging purposes
print_velocities: False

# True for calculating targets
# False for just wandering
calculate_target: True

# Topics to read and post data
# Subscribers
laser_topic: '/robot0/laser_0'
sonar_front_topic: '/robot0/sonar_0'
sonar_left_topic: '/robot0/sonar_1'
sonar_right_topic: '/robot0/sonar_2'
sonar_rear_left_topic: '/robot0/sonar_3'
sonar_rear_right_topic: '/robot0/sonar_4'
ogm_topic: '/slam/occupancyGridMap'

# Publishers
coverage_pub_topic: '/as/robot/coverage'
speeds_pub_topic: '/robot0/cmd_vel'
robot_trajectory_topic: '/as/robot/trajectory'
path_pub_topic: '/as/path'
subgoals_pub_topic: '/as/subgoals'
curr_target_pub_topic: '/as/current_target'
goals_pub_topic: '/as/goals'

# Frames
map_frame: '/map'
base_footprint_frame: '/base_footprint'

# Cell Size 10, 20, 30, 50
cell_size: 20

# Time (seconds)
time_limit: 60
